# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8f85212b0623b74a63bb8734f90075aa13beb477d56cf70cb1ca823f9ff49cbc5bacdd8b5fc90a9729a40a7833818ed727b5360c912f800b87f15f42bc8417f

test:
  secret_key_base: 3be9a53489b1c0983ee4fbfeb49f88320443645793cf585f4567cf3cd80998a2081147c391df840d98cbf2b4b2c70459bd3428a2b5f5eb2894c74f189b3468b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
